[window]
dimensions = { columns = 120, lines = 40 }
opacity = 0.92

[font]
normal = { family = "Terminess Nerd Font", style = "Regular" }
bold = { family = "Terminess Nerd Font", style = "Bold" }
italic = { family = "Terminess Nerd Font", style = "Italic" }
bold_italic = { family = "Terminess Nerd Font", style = "Bold Italic" }
size = 16

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[colors.primary]
background = '#000000'
foreground = '#d3d7cf'

[colors.normal]
black = '#2e3436'
red = '#cc0000'
green = '#4e9a06'
yellow = '#c4a000'
blue = '#3465a4'
magenta = '#75507b'
cyan = '#06989a'
white = '#d3d7cf'

[colors.bright]
black = '#555753'
red = '#ef2929'
green = '#8ae234'
yellow = '#fce94f'
blue = '#729fcf'
magenta = '#ad7fa8'
cyan = '#34e2e2'
white = '#eeeeec'
