#!/bin/bash

if xrandr | grep -q "^USB-C-0 connected"; then
    xrandr --output USB-C-0 --primary --mode 3840x2160 --pos 0x0 --rotate normal --rate 59.94
else
    xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x400 --rotate normal --output DP-2 --mode 2560x1440 --pos 3840x0 --rotate right
fi
