#!/bin/bash

xrandr --output HDMI-0 --primary --mode 3840x2160 --pos 0x200 --rotate normal --output DP-2 --mode 2560x1440 --pos 3840x0 --rotate right --output USB-C-0 --mode 1024x600 --pos 5280x1536 --rotate left
