#!/bin/bash

weston --socket=wayland-waydroid --width 540 --height 1200 &
WESTON_PID=$!
sleep 1.5

WAYLAND_DISPLAY=wayland-waydroid waydroid show-full-ui &
WAYDROID_PID=$!

trap "waydroid session stop; kill $WESTON_PID" EXIT

wait $WESTON_PID
waydroid session stop
